BGG_DATABASE = {
    1: {
        "name": "Chess",
        "name_zh": "國際象棋",
        "description": "A classic two-player abstract strategy game where each player commands an army of 16 pieces on an 8x8 board.",
        "description_zh": "經典的雙人抽象策略遊戲，每位玩家指揮16枚棋子在8x8棋盤上對弈。",
        "year_published": -500,
        "min_players": 2,
        "max_players": 2,
        "playing_time": 60,
        "min_age": 6,
        "bgg_rating": 6.42,
        "rank": None,
        "mechanics": ["Grid Movement", "Pattern Movement"],
        "categories": ["Abstract Strategy"],
        "designers": [],
        "artists": [],
        "publishers": [],
    },
    2: {
        "name": "Go",
        "name_zh": "圍棋",
        "description": "An ancient abstract strategy game where players place stones on a grid to control territory.",
        "description_zh": "古老的抽象策略遊戲，玩家在棋盤上放置石子以控制領地。",
        "year_published": -2200,
        "min_players": 2,
        "max_players": 2,
        "playing_time": 60,
        "min_age": 8,
        "bgg_rating": 7.66,
        "rank": None,
        "mechanics": ["Area Control", "Network Building"],
        "categories": ["Abstract Strategy"],
        "designers": [],
        "artists": [],
        "publishers": [],
    },
    4: {
        "name": "Monopoly",
        "name_zh": "大富翁",
        "description": "Roll-and-move game about buying, trading, and developing properties to bankrupt opponents.",
        "description_zh": "擲骰移動的買地建屋遊戲，目標是讓對手破產。",
        "year_published": 1935,
        "min_players": 2,
        "max_players": 8,
        "playing_time": 90,
        "min_age": 8,
        "bgg_rating": 4.43,
        "rank": None,
        "mechanics": ["Roll / Spin and Move", "Set Collection", "Trading"],
        "categories": ["Economic", "Negotiation"],
        "designers": ["Charles Darrow"],
        "artists": [],
        "publishers": ["Hasbro", "Parker Brothers"],
    },
    5: {
        "name": "Backgammon",
        "name_zh": "雙陸棋",
        "description": "One of the oldest board games, combining strategy and luck as players race to bear off all their checkers.",
        "description_zh": "最古老的棋盤遊戲之一，結合策略與運氣，玩家競速將所有棋子移出棋盤。",
        "year_published": -3000,
        "min_players": 2,
        "max_players": 2,
        "playing_time": 30,
        "min_age": 8,
        "bgg_rating": 6.15,
        "rank": None,
        "mechanics": ["Dice Rolling", "Press Your Luck"],
        "categories": ["Abstract Strategy"],
        "designers": [],
        "artists": [],
        "publishers": [],
    },
    7: {
        "name": "Chinese Checkers",
        "name_zh": "跳棋",
        "description": "A strategy board game where players race their pieces across a star-shaped board to the opposite corner.",
        "description_zh": "策略棋盤遊戲，玩家競速將棋子越過星形棋盤到對角。",
        "year_published": 1892,
        "min_players": 2,
        "max_players": 6,
        "playing_time": 30,
        "min_age": 6,
        "bgg_rating": 5.21,
        "rank": None,
        "mechanics": ["Grid Movement", "Pattern Movement"],
        "categories": ["Abstract Strategy"],
        "designers": [],
        "artists": [],
        "publishers": [],
    },
    8: {
        "name": "Mahjong",
        "name_zh": "麻將",
        "description": "A tile-based game of skill, strategy, and calculation, where players draw and discard tiles to form winning combinations.",
        "description_zh": "基於技巧、策略與計算的牌類遊戲，玩家摸牌打牌組成胡牌牌型。",
        "year_published": 1850,
        "min_players": 2,
        "max_players": 4,
        "playing_time": 60,
        "min_age": 8,
        "bgg_rating": 5.88,
        "rank": None,
        "mechanics": ["Set Collection", "Tile Placement"],
        "categories": ["Abstract Strategy"],
        "designers": [],
        "artists": [],
        "publishers": [],
    },
    9: {
        "name": "Othello",
        "name_zh": "黑白棋",
        "description": "A two-player abstract strategy game where players place discs to flip opponent pieces on an 8x8 board.",
        "description_zh": "雙人抽象策略遊戲，玩家在8x8棋盤上放置棋子翻轉對手的棋子。",
        "year_published": 1883,
        "min_players": 2,
        "max_players": 2,
        "playing_time": 30,
        "min_age": 8,
        "bgg_rating": 5.97,
        "rank": None,
        "mechanics": ["Area Control", "Pattern Movement"],
        "categories": ["Abstract Strategy"],
        "designers": [],
        "artists": [],
        "publishers": [],
    },
    10: {
        "name": "Xiangqi",
        "name_zh": "象棋",
        "description": "Chinese Chess, a two-player strategy board game simulating a battle between two armies.",
        "description_zh": "中國象棋，雙人策略棋盤遊戲，模擬兩軍對戰。",
        "year_published": -200,
        "min_players": 2,
        "max_players": 2,
        "playing_time": 60,
        "min_age": 8,
        "bgg_rating": 6.37,
        "rank": None,
        "mechanics": ["Grid Movement", "Pattern Movement"],
        "categories": ["Abstract Strategy"],
        "designers": [],
        "artists": [],
        "publishers": [],
    },
    11: {
        "name": "The Game of Life",
        "name_zh": "人生遊戲",
        "description": "A classic family game where players travel through life stages, making choices about career and family.",
        "description_zh": "經典家庭遊戲，玩家經歷人生各階段，做職業與家庭選擇。",
        "year_published": 1960,
        "min_players": 2,
        "max_players": 6,
        "playing_time": 60,
        "min_age": 9,
        "bgg_rating": 4.08,
        "rank": None,
        "mechanics": ["Roll / Spin and Move"],
        "categories": ["Family"],
        "designers": ["Reuben Klamer"],
        "artists": [],
        "publishers": ["Hasbro", "Milton Bradley"],
    },
    12: {
        "name": "Scrabble",
        "name_zh": "拼字遊戲",
        "description": "A word game where players score points by placing letter tiles on a board to form interlocking words.",
        "description_zh": "文字遊戲，玩家在棋盤上放置字母牌組成連鎖單字來得分。",
        "year_published": 1948,
        "min_players": 2,
        "max_players": 4,
        "playing_time": 90,
        "min_age": 10,
        "bgg_rating": 5.65,
        "rank": None,
        "mechanics": ["Tile Placement"],
        "categories": ["Word Game"],
        "designers": ["Alfred Mosher Butts"],
        "artists": [],
        "publishers": ["Hasbro", "Mattel"],
    },
    13: {
        "name": "Catan",
        "name_zh": "卡坦島",
        "description": "Players build settlements and cities, trade resources, and compete for the largest civilization on the island of Catan.",
        "description_zh": "玩家在卡坦島上建設聚落與城市、交易資源，競爭最大文明。",
        "year_published": 1995,
        "min_players": 3,
        "max_players": 4,
        "playing_time": 75,
        "min_age": 10,
        "bgg_rating": 7.19,
        "rank": 284,
        "mechanics": ["Dice Rolling", "Modular Board", "Network Building", "Trading"],
        "categories": ["Negotiation", "Economic"],
        "designers": ["Klaus Teuber"],
        "artists": ["Michael Menzel"],
        "publishers": ["Kosmos", "Mayfair Games", "Catan Studio"],
    },
    15: {
        "name": "Parcheesi",
        "name_zh": "帕奇西",
        "description": "A classic race game where players move pawns around a cross-shaped board to reach home.",
        "description_zh": "經典競速遊戲，玩家在十字形棋盤上移動棋子回家。",
        "year_published": 1874,
        "min_players": 2,
        "max_players": 4,
        "playing_time": 45,
        "min_age": 6,
        "bgg_rating": 4.56,
        "rank": None,
        "mechanics": ["Dice Rolling", "Roll / Spin and Move"],
        "categories": ["Race"],
        "designers": [],
        "artists": [],
        "publishers": [],
    },
    18: {
        "name": "Snakes and Ladders",
        "name_zh": "蛇梯棋",
        "description": "A simple children's race game where players climb ladders and slide down snakes on a numbered board.",
        "description_zh": "簡單的兒童競速遊戲，玩家在數字棋盤上爬梯子、滑蛇道。",
        "year_published": 1943,
        "min_players": 2,
        "max_players": 6,
        "playing_time": 15,
        "min_age": 3,
        "bgg_rating": 2.81,
        "rank": None,
        "mechanics": ["Dice Rolling", "Roll / Spin and Move"],
        "categories": ["Children's Game"],
        "designers": [],
        "artists": [],
        "publishers": [],
    },
    21: {
        "name": "Candy Land",
        "name_zh": "糖果世界",
        "description": "A simple children's game where players race through a candy-themed board using color cards.",
        "description_zh": "簡單的兒童遊戲，玩家用顏色牌在糖果主題棋盤上競速。",
        "year_published": 1949,
        "min_players": 2,
        "max_players": 4,
        "playing_time": 15,
        "min_age": 3,
        "bgg_rating": 2.57,
        "rank": None,
        "mechanics": ["Card Drafting", "Race"],
        "categories": ["Children's Game"],
        "designers": ["Eleanor Abbott"],
        "artists": [],
        "publishers": ["Hasbro", "Milton Bradley"],
    },
    22: {
        "name": "Connect Four",
        "name_zh": "四子棋",
        "description": "A two-player connection game where players drop colored discs into a vertical grid, aiming to connect four in a row.",
        "description_zh": "雙人連線遊戲，玩家在垂直網格中投入彩色棋子，目標連成四子。",
        "year_published": 1974,
        "min_players": 2,
        "max_players": 2,
        "playing_time": 10,
        "min_age": 6,
        "bgg_rating": 4.62,
        "rank": None,
        "mechanics": ["Grid Movement", "Pattern Building"],
        "categories": ["Abstract Strategy"],
        "designers": ["Howard Wexler"],
        "artists": [],
        "publishers": ["Hasbro", "Milton Bradley"],
    },
    27: {
        "name": "Samurai",
        "name_zh": "武士",
        "description": "A tile-placement game where players compete to influence the three castes of feudal Japan.",
        "description_zh": "板塊放置遊戲，玩家在封建日本的三個階層中競爭影響力。",
        "year_published": 1998,
        "min_players": 2,
        "max_players": 4,
        "playing_time": 45,
        "min_age": 10,
        "bgg_rating": 6.99,
        "rank": None,
        "mechanics": ["Area Control", "Tile Placement"],
        "categories": ["Abstract Strategy"],
        "designers": ["Reiner Knizia"],
        "artists": ["Julien Delval"],
        "publishers": ["Hans im Glück", "Rio Grande Games"],
    },
    29: {
        "name": "Operation",
        "name_zh": "手術遊戲",
        "description": "A dexterity game where players use tweezers to remove body parts from a patient without touching the sides.",
        "description_zh": "靈巧遊戲，玩家用鑷子取出病人的身體部位，不能碰到邊緣。",
        "year_published": 1965,
        "min_players": 1,
        "max_players": 6,
        "playing_time": 15,
        "min_age": 6,
        "bgg_rating": 3.28,
        "rank": None,
        "mechanics": ["Action / Dexterity", "Real-Time"],
        "categories": ["Children's Game"],
        "designers": ["John Spinello"],
        "artists": [],
        "publishers": ["Hasbro", "Milton Bradley"],
    },
    30: {
        "name": "Battleship",
        "name_zh": "海戰棋",
        "description": "A classic guessing game where players try to sink each other's hidden fleet of ships.",
        "description_zh": "經典猜謎遊戲，玩家試圖擊沉對方隱藏的艦隊。",
        "year_published": 1967,
        "min_players": 2,
        "max_players": 2,
        "playing_time": 30,
        "min_age": 8,
        "bgg_rating": 4.29,
        "rank": None,
        "mechanics": ["Deduction", "Grid Coverage", "Secret Unit Deployment"],
        "categories": ["Deduction"],
        "designers": [],
        "artists": [],
        "publishers": ["Hasbro", "Milton Bradley"],
    },
    31: {
        "name": "Guess Who?",
        "name_zh": "猜猜他是誰",
        "description": "A two-player deduction game where players ask yes/no questions to identify a mystery character.",
        "description_zh": "雙人推理遊戲，玩家用是非題找出神秘角色。",
        "year_published": 1979,
        "min_players": 2,
        "max_players": 2,
        "playing_time": 10,
        "min_age": 6,
        "bgg_rating": 3.91,
        "rank": None,
        "mechanics": ["Deduction"],
        "categories": ["Deduction", "Children's Game"],
        "designers": ["Theo Coster", "Ora Coster"],
        "artists": [],
        "publishers": ["Hasbro", "Milton Bradley"],
    },
    38: {
        "name": "Pictionary",
        "name_zh": "比手畫腳",
        "description": "A team-based drawing game where players sketch clues for teammates to guess words or phrases.",
        "description_zh": "團隊繪畫遊戲，玩家畫出線索讓隊友猜出詞語。",
        "year_published": 1985,
        "min_players": 3,
        "max_players": 16,
        "playing_time": 45,
        "min_age": 12,
        "bgg_rating": 4.75,
        "rank": None,
        "mechanics": ["Acting", "Drawing", "Paper-and-Pencil"],
        "categories": ["Party Game"],
        "designers": ["Robert Angel"],
        "artists": [],
        "publishers": ["Hasbro", "Mattel"],
    },
    39: {
        "name": "Trouble",
        "name_zh": "麻煩",
        "description": "A pop-o-matic dice race game where players move pegs around the board to reach home.",
        "description_zh": "按壓式骰子競速遊戲，玩家移動棋子回家。",
        "year_published": 1965,
        "min_players": 2,
        "max_players": 4,
        "playing_time": 30,
        "min_age": 5,
        "bgg_rating": 3.55,
        "rank": None,
        "mechanics": ["Dice Rolling", "Roll / Spin and Move"],
        "categories": ["Children's Game", "Race"],
        "designers": [],
        "artists": [],
        "publishers": ["Hasbro", "Milton Bradley"],
    },
    41: {
        "name": "Boggle",
        "name_zh": "刮刮樂",
        "description": "A timed word search game where players find words in a grid of random letter cubes.",
        "description_zh": "計時文字搜索遊戲，玩家在隨機字母方塊中找出單字。",
        "year_published": 1972,
        "min_players": 1,
        "max_players": 8,
        "playing_time": 10,
        "min_age": 8,
        "bgg_rating": 5.21,
        "rank": None,
        "mechanics": ["Pattern Recognition", "Real-Time"],
        "categories": ["Word Game", "Real-time"],
        "designers": ["Allan Turoff"],
        "artists": [],
        "publishers": ["Hasbro", "Parker Brothers"],
    },
    42: {
        "name": "Tigris & Euphrates",
        "name_zh": "底格里斯與幼發拉底",
        "description": "A tile-placement game of civilization building in ancient Mesopotamia, balancing four spheres of influence.",
        "description_zh": "在古美索不達米亞建設文明的板塊放置遊戲，平衡四種影響力。",
        "year_published": 1997,
        "min_players": 2,
        "max_players": 4,
        "playing_time": 90,
        "min_age": 12,
        "bgg_rating": 7.45,
        "rank": None,
        "mechanics": ["Area Control", "Tile Placement", "Conflict"],
        "categories": ["Civilization", "Territory Building"],
        "designers": ["Reiner Knizia"],
        "artists": ["Doris Matthäus"],
        "publishers": ["Hans im Glück", "Rio Grande Games", "FFG"],
    },
    44: {
        "name": "Sorry!",
        "name_zh": "對不起",
        "description": "A card-driven race game where players move pawns around the board, bumping opponents back to start.",
        "description_zh": "卡牌驅動的競速遊戲，玩家在棋盤上移動棋子，撞擊對手回到起點。",
        "year_published": 1934,
        "min_players": 2,
        "max_players": 4,
        "playing_time": 45,
        "min_age": 6,
        "bgg_rating": 3.72,
        "rank": None,
        "mechanics": ["Card Drafting", "Dice Rolling", "Roll / Spin and Move"],
        "categories": ["Children's Game", "Race"],
        "designers": [],
        "artists": [],
        "publishers": ["Hasbro", "Parker Brothers"],
    },
    47: {
        "name": "Acquire",
        "name_zh": "併購",
        "description": "A classic economic game of hotel chain investment, mergers, and stock trading.",
        "description_zh": "經典經濟遊戲，涉及連鎖酒店投資、併購與股票交易。",
        "year_published": 1962,
        "min_players": 3,
        "max_players": 6,
        "playing_time": 90,
        "min_age": 12,
        "bgg_rating": 6.74,
        "rank": None,
        "mechanics": ["Investment", "Stock Holding", "Tile Placement"],
        "categories": ["Economic"],
        "designers": ["Sid Sackson"],
        "artists": [],
        "publishers": ["3M", "Avalon Hill", "Hasbro"],
    },
    48: {
        "name": "Mancala",
        "name_zh": "曼卡拉",
        "description": "An ancient family of seed-sowing board games played across Africa and Asia.",
        "description_zh": "古老的播種棋盤遊戲家族，遍及非洲與亞洲。",
        "year_published": -6000,
        "min_players": 2,
        "max_players": 2,
        "playing_time": 20,
        "min_age": 6,
        "bgg_rating": 5.77,
        "rank": None,
        "mechanics": ["Set Collection"],
        "categories": ["Abstract Strategy"],
        "designers": [],
        "artists": [],
        "publishers": [],
    },
    55: {
        "name": "Cribbage",
        "name_zh": "克里比奇",
        "description": "A classic card game combining hand management and a pegboard scoring system.",
        "description_zh": "經典紙牌遊戲，結合手牌管理與計分板系統。",
        "year_published": 1630,
        "min_players": 2,
        "max_players": 4,
        "playing_time": 30,
        "min_age": 10,
        "bgg_rating": 6.38,
        "rank": None,
        "mechanics": ["Hand Management", "Set Collection"],
        "categories": ["Card Game"],
        "designers": ["John Suckling"],
        "artists": [],
        "publishers": [],
    },
    68: {
        "name": "Can't Stop",
        "name_zh": "停不下來",
        "description": "A push-your-luck dice game where players race to claim columns on the board by rolling specific number combinations.",
        "description_zh": "考驗膽量的骰子遊戲，玩家滾骰搶佔棋盤上的列。",
        "year_published": 1980,
        "min_players": 2,
        "max_players": 4,
        "playing_time": 30,
        "min_age": 9,
        "bgg_rating": 6.56,
        "rank": None,
        "mechanics": ["Dice Rolling", "Push Your Luck"],
        "categories": ["Dice"],
        "designers": ["Sid Sackson"],
        "artists": [],
        "publishers": ["Parker Brothers", "Eagle-Gryphon Games"],
    },
    71: {
        "name": "Cluedo",
        "name_zh": "妙探尋兇",
        "description": "A classic deduction game where players solve a murder by identifying the suspect, weapon, and room.",
        "description_zh": "經典推理遊戲，玩家找出嫌疑犯、凶器與案發房間來破案。",
        "year_published": 1949,
        "min_players": 3,
        "max_players": 6,
        "playing_time": 45,
        "min_age": 8,
        "bgg_rating": 4.99,
        "rank": None,
        "mechanics": ["Deduction", "Grid Movement", "Roll / Spin and Move"],
        "categories": ["Deduction", "Murder/Mystery"],
        "designers": ["Anthony E. Pratt"],
        "artists": [],
        "publishers": ["Hasbro", "Parker Brothers", "Waddingtons"],
    },
    88: {
        "name": "Hare and Tortoise",
        "name_zh": "龜兔賽跑",
        "description": "A unique racing game where moving faster costs more energy, creating a strategic balance.",
        "description_zh": "獨特競速遊戲，移動越快消耗越多能量，創造策略平衡。",
        "year_published": 1974,
        "min_players": 2,
        "max_players": 6,
        "playing_time": 45,
        "min_age": 10,
        "bgg_rating": 6.01,
        "rank": None,
        "mechanics": ["Movement Points", "Race"],
        "categories": ["Racing"],
        "designers": ["David Parlett"],
        "artists": [],
        "publishers": ["Gibson Games", "Rio Grande Games"],
    },
    115: {
        "name": "Zertz",
        "name_zh": "策爾茨",
        "description": "An abstract strategy game in the GIPF series where players place and jump marbles to collect sets.",
        "description_zh": "GIPF系列中的抽象策略遊戲，玩家放置和跳躍彈珠以收集套組。",
        "year_published": 2000,
        "min_players": 2,
        "max_players": 2,
        "playing_time": 30,
        "min_age": 9,
        "bgg_rating": 6.87,
        "rank": None,
        "mechanics": ["Pattern Movement", "Set Collection"],
        "categories": ["Abstract Strategy"],
        "designers": ["Kris Burm"],
        "artists": [],
        "publishers": ["Rio Grande Games", "Smart Games"],
    },
    134: {
        "name": "Taboo",
        "name_zh": "禁忌",
        "description": "A party game where players describe a word without using certain forbidden words.",
        "description_zh": "派對遊戲，玩家描述一個詞但不能使用特定的禁忌詞。",
        "year_published": 1989,
        "min_players": 4,
        "max_players": 10,
        "playing_time": 20,
        "min_age": 12,
        "bgg_rating": 5.03,
        "rank": None,
        "mechanics": ["Acting", "Real-Time", "Time Track"],
        "categories": ["Party Game"],
        "designers": ["Brian Hersch"],
        "artists": [],
        "publishers": ["Hasbro", "Milton Bradley"],
    },
    141: {
        "name": "Focus",
        "name_zh": "焦點",
        "description": "An abstract strategy game of stacking and capturing pieces on a shrinking board.",
        "description_zh": "在縮小的棋盤上堆疊和吃子的抽象策略遊戲。",
        "year_published": 1963,
        "min_players": 2,
        "max_players": 4,
        "playing_time": 45,
        "min_age": 10,
        "bgg_rating": 6.22,
        "rank": None,
        "mechanics": ["Area Control", "Stacking"],
        "categories": ["Abstract Strategy"],
        "designers": ["Sid Sackson"],
        "artists": [],
        "publishers": ["3M", "Parker Brothers"],
    },
    151: {
        "name": "Dvonn",
        "name_zh": "德翁",
        "description": "A stacking abstract game in the GIPF series where pieces must stay connected to the Dvonn pieces.",
        "description_zh": "GIPF系列中的堆疊抽象遊戲，棋子必須與Dvonn棋子保持連接。",
        "year_published": 2001,
        "min_players": 2,
        "max_players": 2,
        "playing_time": 30,
        "min_age": 9,
        "bgg_rating": 6.87,
        "rank": None,
        "mechanics": ["Stacking", "Network Building"],
        "categories": ["Abstract Strategy"],
        "designers": ["Kris Burm"],
        "artists": [],
        "publishers": ["Rio Grande Games", "Smart Games"],
    },
    157: {
        "name": "Bridge",
        "name_zh": "橋牌",
        "description": "A classic trick-taking card game for four players in two partnerships.",
        "description_zh": "經典四人兩組的吃墩紙牌遊戲。",
        "year_published": 1925,
        "min_players": 4,
        "max_players": 4,
        "playing_time": 90,
        "min_age": 10,
        "bgg_rating": 6.58,
        "rank": None,
        "mechanics": ["Trick-taking", "Partnerships", "Bidding"],
        "categories": ["Card Game"],
        "designers": ["Harold Vanderbilt"],
        "artists": [],
        "publishers": [],
    },
    170: {
        "name": "Poker",
        "name_zh": "撲克",
        "description": "A family of card games combining gambling, strategy, and skill with various hand rankings.",
        "description_zh": "結合賭博、策略與技巧的紙牌遊戲家族，有多種牌型排名。",
        "year_published": 1829,
        "min_players": 2,
        "max_players": 10,
        "playing_time": 60,
        "min_age": 18,
        "bgg_rating": 6.10,
        "rank": None,
        "mechanics": ["Betting", "Bluffing", "Hand Management"],
        "categories": ["Card Game"],
        "designers": [],
        "artists": [],
        "publishers": [],
    },
    173: {
        "name": "Hearts",
        "name_zh": "紅心大戰",
        "description": "A classic trick-avoidance card game where players try to avoid taking hearts and the Queen of Spades.",
        "description_zh": "經典的避墩紙牌遊戲，玩家要避免吃到紅心和黑桃皇后。",
        "year_published": 1850,
        "min_players": 3,
        "max_players": 7,
        "playing_time": 30,
        "min_age": 10,
        "bgg_rating": 5.71,
        "rank": None,
        "mechanics": ["Trick-taking", "Card Drafting"],
        "categories": ["Card Game"],
        "designers": [],
        "artists": [],
        "publishers": [],
    },
    193: {
        "name": "Spades",
        "name_zh": "黑桃",
        "description": "A trick-taking card game where players bid on the number of tricks they will take.",
        "description_zh": "吃墩紙牌遊戲，玩家競標要吃的墩數。",
        "year_published": 1937,
        "min_players": 4,
        "max_players": 4,
        "playing_time": 30,
        "min_age": 10,
        "bgg_rating": 5.76,
        "rank": None,
        "mechanics": ["Bidding", "Trick-taking", "Partnerships"],
        "categories": ["Card Game"],
        "designers": [],
        "artists": [],
        "publishers": [],
    },
    194: {
        "name": "Solitaire",
        "name_zh": "接龍",
        "description": "A single-player card game of sorting cards into foundation piles by suit and rank.",
        "description_zh": "單人紙牌遊戲，按花色和大小將牌排入基礎堆。",
        "year_published": 1783,
        "min_players": 1,
        "max_players": 1,
        "playing_time": 20,
        "min_age": 8,
        "bgg_rating": 4.67,
        "rank": None,
        "mechanics": ["Set Collection", "Stacking"],
        "categories": ["Card Game"],
        "designers": [],
        "artists": [],
        "publishers": [],
    },
    240: {
        "name": "Elfenland",
        "name_zh": "精靈國度",
        "description": "A route-building game set in a fantasy world where players travel using various transportation modes.",
        "description_zh": "在奇幻世界中的路線建設遊戲，玩家用各種交通工具旅行。",
        "year_published": 1998,
        "min_players": 2,
        "max_players": 6,
        "playing_time": 60,
        "min_age": 10,
        "bgg_rating": 6.31,
        "rank": None,
        "mechanics": ["Card Drafting", "Route/Network Building"],
        "categories": ["Fantasy", "Route/Network Building"],
        "designers": ["Alan R. Moon"],
        "artists": ["Doris Matthäus"],
        "publishers": ["Amigo", "Rio Grande Games"],
    },
    540: {
        "name": "Lord of the Rings",
        "name_zh": "魔戒",
        "description": "A cooperative game where players take on the roles of hobbits working together to destroy the One Ring.",
        "description_zh": "合作遊戲，玩家扮演哈比人共同摧毀至尊魔戒。",
        "year_published": 2000,
        "min_players": 2,
        "max_players": 5,
        "playing_time": 90,
        "min_age": 12,
        "bgg_rating": 6.49,
        "rank": None,
        "mechanics": ["Cooperative Play", "Hand Management"],
        "categories": ["Adventure", "Fantasy"],
        "designers": ["Reiner Knizia"],
        "artists": ["John Howe"],
        "publishers": ["FFG", "Kosmos"],
    },
    822: {
        "name": "Carcassonne",
        "name_zh": "卡卡頌",
        "description": "A tile-placement game where players build a medieval landscape of cities, roads, monasteries, and fields.",
        "description_zh": "板塊放置遊戲，玩家建造中世紀城市、道路、修道院與田野景觀。",
        "year_published": 2000,
        "min_players": 2,
        "max_players": 5,
        "playing_time": 45,
        "min_age": 8,
        "bgg_rating": 7.44,
        "rank": 254,
        "mechanics": ["Tile Placement", "Area Control"],
        "categories": ["City Building", "Medieval"],
        "designers": ["Klaus-Jürgen Wrede"],
        "artists": ["Doris Matthäus"],
        "publishers": ["Hans im Glück", "Rio Grande Games", "Z-Man Games"],
    },
    915: {
        "name": "Wyatt Earp",
        "name_zh": "懷特厄普",
        "description": "A rummy-style card game set in the Wild West about capturing outlaws for bounties.",
        "description_zh": "西部荒野的拉米牌遊戲，玩家捉拿亡命之徒領取賞金。",
        "year_published": 2001,
        "min_players": 2,
        "max_players": 4,
        "playing_time": 45,
        "min_age": 12,
        "bgg_rating": 6.33,
        "rank": None,
        "mechanics": ["Set Collection", "Card Drafting"],
        "categories": ["Card Game", "Western"],
        "designers": ["Richard Borg", "Mike Selinker"],
        "artists": [],
        "publishers": ["Avalon Hill"],
    },
    1209: {
        "name": "Torres",
        "name_zh": "塔樓",
        "description": "A tower-building game where players construct castles and place knights to score points.",
        "description_zh": "建塔遊戲，玩家建造城堡並放置騎士得分。",
        "year_published": 1999,
        "min_players": 2,
        "max_players": 5,
        "playing_time": 75,
        "min_age": 12,
        "bgg_rating": 6.61,
        "rank": None,
        "mechanics": ["Action Points", "Area Control", "Tile Placement"],
        "categories": ["Medieval"],
        "designers": ["Michael Kiesling", "Wolfgang Kramer"],
        "artists": [],
        "publishers": ["FX", "Rio Grande Games"],
    },
    1406: {
        "name": "Vinci",
        "name_zh": "文藝復興",
        "description": "A civilization game where players lead successive empires in ancient Europe, declining and rising again.",
        "description_zh": "文明遊戲，玩家在古歐洲領導先後的帝國，衰退後再崛起。",
        "year_published": 1999,
        "min_players": 3,
        "max_players": 6,
        "playing_time": 90,
        "min_age": 12,
        "bgg_rating": 6.62,
        "rank": None,
        "mechanics": ["Area Control", "Auction/Bidding", "Variable Player Powers"],
        "categories": ["Civilization", "Territory Building"],
        "designers": ["Philippe Keyaerts"],
        "artists": [],
        "publishers": ["Descartes", "Rio Grande Games"],
    },
    2651: {
        "name": "Power Grid",
        "name_zh": "電力網路",
        "description": "An economic game where players bid on power plants, buy resources, and build networks to power cities.",
        "description_zh": "經濟遊戲，玩家競標電廠、購買資源、建設網路為城市供電。",
        "year_published": 2004,
        "min_players": 2,
        "max_players": 6,
        "playing_time": 120,
        "min_age": 12,
        "bgg_rating": 7.52,
        "rank": 182,
        "mechanics": ["Auction/Bidding", "Network Building", "Route/Network Building"],
        "categories": ["Economic"],
        "designers": ["Friedemann Friese"],
        "artists": ["Mia Steingräber"],
        "publishers": ["2F-Spiele", "Rio Grande Games"],
    },
    3076: {
        "name": "Puerto Rico",
        "name_zh": "波多黎各",
        "description": "Players take on roles to build plantations, produce goods, and ship them for victory points.",
        "description_zh": "玩家扮演角色建造莊園、生產商品並運送換取勝利點數。",
        "year_published": 2002,
        "min_players": 2,
        "max_players": 5,
        "playing_time": 90,
        "min_age": 12,
        "bgg_rating": 7.71,
        "rank": 97,
        "mechanics": ["Role Playing", "Variable Phase Order", "Set Collection"],
        "categories": ["Economic", "Farming"],
        "designers": ["Andreas Seyfarth"],
        "artists": ["Alexandr Elichev", "Annette Voke"],
        "publishers": ["Alea", "Rio Grande Games"],
    },
    31260: {
        "name": "Agricola",
        "name_zh": "農家樂",
        "description": "A farming game where players build a farmstead, grow crops, and raise livestock to feed their family.",
        "description_zh": "農場經營遊戲，玩家建造農莊、種植作物、飼養牲畜養活家人。",
        "year_published": 2007,
        "min_players": 1,
        "max_players": 5,
        "playing_time": 90,
        "min_age": 12,
        "bgg_rating": 7.76,
        "rank": 74,
        "mechanics": ["Action Points", "Occupation/Improvement", "Worker Placement"],
        "categories": ["Economic", "Farming"],
        "designers": ["Uwe Rosenberg"],
        "artists": ["Klemens Franz"],
        "publishers": ["Lookout Games", "Z-Man Games"],
    },
    30549: {
        "name": "Pandemic",
        "name_zh": "瘟疫危機",
        "description": "A cooperative game where players work together to cure four diseases spreading across the globe.",
        "description_zh": "合作遊戲，玩家合作治療在全球蔓延的四種疾病。",
        "year_published": 2008,
        "min_players": 2,
        "max_players": 4,
        "playing_time": 60,
        "min_age": 10,
        "bgg_rating": 7.63,
        "rank": 124,
        "mechanics": ["Action Points", "Cooperative Play", "Hand Management", "Set Collection"],
        "categories": ["Medical"],
        "designers": ["Matt Leacock"],
        "artists": ["Chris Quilliams"],
        "publishers": ["Z-Man Games"],
    },
    35677: {
        "name": "Le Havre",
        "name_zh": "勒哈佛",
        "description": "A worker-placement game about building a harbor empire in the French port city.",
        "description_zh": "工人放置遊戲，在法國港口城市建立港口帝國。",
        "year_published": 2008,
        "min_players": 1,
        "max_players": 5,
        "playing_time": 150,
        "min_age": 12,
        "bgg_rating": 7.56,
        "rank": 149,
        "mechanics": ["Worker Placement", "Building"],
        "categories": ["Economic"],
        "designers": ["Uwe Rosenberg"],
        "artists": ["Klemens Franz"],
        "publishers": ["Lookout Games", "Z-Man Games"],
    },
    36218: {
        "name": "Dominion",
        "name_zh": "皇輿爭霸",
        "description": "The original deck-building game where players start with a weak deck and acquire better cards to score points.",
        "description_zh": "原創牌組構築遊戲，玩家從弱牌組開始，購買更好的牌來得分。",
        "year_published": 2008,
        "min_players": 2,
        "max_players": 4,
        "playing_time": 30,
        "min_age": 10,
        "bgg_rating": 7.25,
        "rank": 314,
        "mechanics": ["Deck, Bag, and Pool Building"],
        "categories": ["Card Game"],
        "designers": ["Donald X. Vaccarino"],
        "artists": [],
        "publishers": ["Rio Grande Games"],
    },
    47868: {
        "name": "Letters from Whitechapel",
        "name_zh": "白教堂來信",
        "description": "A deduction game where Jack the Ripper tries to evade detectives in Victorian London.",
        "description_zh": "推理遊戲，開膛手傑克試圖在維多利亞倫敦逃離警探追捕。",
        "year_published": 2011,
        "min_players": 2,
        "max_players": 6,
        "playing_time": 120,
        "min_age": 13,
        "bgg_rating": 7.13,
        "rank": None,
        "mechanics": ["Deduction", "Hidden Movement", "Secret Unit Deployment"],
        "categories": ["Deduction", "Murder/Mystery"],
        "designers": ["Francesco Nepitello", "Marco Maggi"],
        "artists": [],
        "publishers": ["FFG"],
    },
    68448: {
        "name": "7 Wonders",
        "name_zh": "七大奇蹟",
        "description": "A card-drafting game where players build civilizations and construct one of the ancient world's seven wonders.",
        "description_zh": "選牌遊戲，玩家建設文明並建造古代世界七大奇蹟之一。",
        "year_published": 2010,
        "min_players": 2,
        "max_players": 7,
        "playing_time": 30,
        "min_age": 10,
        "bgg_rating": 7.68,
        "rank": 101,
        "mechanics": ["Card Drafting", "Set Collection", "Simultaneous Action Selection"],
        "categories": ["Ancient", "Card Game", "Civilization"],
        "designers": ["Antoine Bauza"],
        "artists": ["Miguel Coimbra"],
        "publishers": ["Repos Production", "Asmodee"],
    },
    89424: {
        "name": "Roll for the Galaxy",
        "name_zh": "銀河路線",
        "description": "A dice game of building a galactic civilization by rolling and assigning dice to various phases.",
        "description_zh": "擲骰建設銀河文明的骰子遊戲。",
        "year_published": 2014,
        "min_players": 2,
        "max_players": 5,
        "playing_time": 45,
        "min_age": 13,
        "bgg_rating": 7.48,
        "rank": None,
        "mechanics": ["Dice Rolling", "Variable Phase Order", "Tile Placement"],
        "categories": ["Science Fiction", "Space Exploration"],
        "designers": ["Thomas Lehmann"],
        "artists": [],
        "publishers": ["Rio Grande Games"],
    },
    96848: {
        "name": "Mage Knight Board Game",
        "name_zh": "法師騎士",
        "description": "An epic adventure game combining deck-building, RPG, and exploration in a fantasy world.",
        "description_zh": "結合牌組構築、角色扮演與探索的史詩冒險遊戲。",
        "year_published": 2011,
        "min_players": 1,
        "max_players": 4,
        "playing_time": 180,
        "min_age": 14,
        "bgg_rating": 8.08,
        "rank": 20,
        "mechanics": ["Deck, Bag, and Pool Building", "Cooperative Play", "Modular Board"],
        "categories": ["Adventure", "Fantasy", "Exploration"],
        "designers": ["Vlaada Chvátil"],
        "artists": ["Marek Blaha", "Jody L. Lisberger"],
        "publishers": ["WizKids"],
    },
    110327: {
        "name": "Lords of Waterdeep",
        "name_zh": "深水城領主",
        "description": "A worker-placement game set in Dungeons & Dragons' Forgotten Realms, where players send agents on quests.",
        "description_zh": "D&D被遺忘國度中的工人放置遊戲，玩家派特工執行任務。",
        "year_published": 2012,
        "min_players": 2,
        "max_players": 5,
        "playing_time": 60,
        "min_age": 12,
        "bgg_rating": 7.49,
        "rank": None,
        "mechanics": ["Worker Placement", "Quests"],
        "categories": ["Fantasy"],
        "designers": ["Peter Lee", "Rodney Thompson"],
        "artists": [],
        "publishers": ["WotC"],
    },
    115746: {
        "name": "War of the Ring (Second Edition)",
        "name_zh": "魔戒聖戰",
        "description": "An epic two-player game recreating the struggle between the Free Peoples and the Shadow in Tolkien's world.",
        "description_zh": "史詩級雙人遊戲，重現托爾金世界中自由民族與暗影的鬥爭。",
        "year_published": 2012,
        "min_players": 2,
        "max_players": 2,
        "playing_time": 180,
        "min_age": 14,
        "bgg_rating": 8.36,
        "rank": 4,
        "mechanics": ["Action Points", "Area Control", "Dice Rolling", "Variable Player Powers"],
        "categories": ["Fantasy", "Fighting", "Miniatures"],
        "designers": ["Roberto Di Meglio", "Francesco Nepitello", "Marco Maggi"],
        "artists": [],
        "publishers": ["Ares Games"],
    },
    12333: {
        "name": "Twilight Struggle",
        "name_zh": "暮光掙扎",
        "description": "A two-player card-driven game simulating the Cold War between the USA and USSR.",
        "description_zh": "雙人卡牌驅動遊戲，模擬美蘇冷戰。",
        "year_published": 2005,
        "min_players": 2,
        "max_players": 2,
        "playing_time": 180,
        "min_age": 13,
        "bgg_rating": 8.22,
        "rank": 6,
        "mechanics": ["Area Control", "Card Drafting", "Campaign Battle"],
        "categories": ["Political", "Wargame"],
        "designers": ["Ananda Gupta", "Jason Matthews"],
        "artists": [],
        "publishers": ["GMT Games"],
    },
    124361: {
        "name": "Concordia",
        "name_zh": "康科迪亞",
        "description": "A peaceful economic strategy game of trading and building across the Roman Empire.",
        "description_zh": "在羅馬帝國進行貿易與建設的和平經濟策略遊戲。",
        "year_published": 2013,
        "min_players": 2,
        "max_players": 5,
        "playing_time": 100,
        "min_age": 12,
        "bgg_rating": 7.95,
        "rank": 29,
        "mechanics": ["Network Building", "Card Drafting"],
        "categories": ["Economic"],
        "designers": ["Mac Gerdts"],
        "artists": [],
        "publishers": ["PD-Verlag", "Rio Grande Games"],
    },
    124742: {
        "name": "Android: Netrunner",
        "name_zh": "仿生人：網路跑者",
        "description": "An asymmetric card game of hackers vs. corporations in a cyberpunk future.",
        "description_zh": "賽博朋克未來中駭客對抗企業的非對稱紙牌遊戲。",
        "year_published": 2012,
        "min_players": 2,
        "max_players": 2,
        "playing_time": 45,
        "min_age": 14,
        "bgg_rating": 7.87,
        "rank": None,
        "mechanics": ["Action Points", "Deck, Bag, and Pool Building", "Variable Player Powers"],
        "categories": ["Science Fiction", "Card Game"],
        "designers": ["Richard Garfield", "Lukas Litzsinger"],
        "artists": [],
        "publishers": ["FFG"],
    },
    129624: {
        "name": "Kingdom Death: Monster",
        "name_zh": "死亡國度",
        "description": "A brutal survival game of hunting monsters and building a settlement in a nightmare world.",
        "description_zh": "在噩夢世界中獵殺怪物、建立聚落的殘酷生存遊戲。",
        "year_published": 2015,
        "min_players": 1,
        "max_players": 4,
        "playing_time": 120,
        "min_age": 17,
        "bgg_rating": 8.44,
        "rank": 2,
        "mechanics": ["Cooperative Play", "Dice Rolling", "Grid Movement", "Storytelling"],
        "categories": ["Adventure", "Fighting", "Horror"],
        "designers": ["Adam Poots"],
        "artists": [],
        "publishers": ["Kingdom Death"],
    },
    136888: {
        "name": "Blood Rage",
        "name_zh": "血怒",
        "description": "A Viking-themed area control game where clans fight for glory before Ragnarok destroys the world.",
        "description_zh": "維京主題區域控制遊戲，部族在世界毀滅前爭奪榮耀。",
        "year_published": 2015,
        "min_players": 2,
        "max_players": 4,
        "playing_time": 90,
        "min_age": 13,
        "bgg_rating": 7.87,
        "rank": 25,
        "mechanics": ["Card Drafting", "Area Control", "Dice Rolling"],
        "categories": ["Fighting", "Mythology"],
        "designers": ["Eric M. Lang"],
        "artists": ["Mihajlo Dimitrievski"],
        "publishers": ["CMON"],
    },
    143943: {
        "name": "Robinson Crusoe: Adventures on the Cursed Island",
        "name_zh": "魯賓遜漂流記",
        "description": "A cooperative survival game where players are shipwrecked on a desert island.",
        "description_zh": "合作生存遊戲，玩家在荒島上遇難求生。",
        "year_published": 2012,
        "min_players": 1,
        "max_players": 4,
        "playing_time": 120,
        "min_age": 14,
        "bgg_rating": 7.69,
        "rank": None,
        "mechanics": ["Cooperative Play", "Worker Placement", "Dice Rolling"],
        "categories": ["Adventure", "Exploration"],
        "designers": ["Ignacy Trzewiczek"],
        "artists": [],
        "publishers": ["Portal Games", "FFG"],
    },
    1500: {
        "name": "Hellas",
        "name_zh": "希臘之海",
        "description": "A two-player card game of naval battles in ancient Greece.",
        "description_zh": "古希臘海戰的雙人紙牌遊戲。",
        "year_published": 2002,
        "min_players": 2,
        "max_players": 2,
        "playing_time": 30,
        "min_age": 10,
        "bgg_rating": 5.87,
        "rank": None,
        "mechanics": ["Card Play", "Hand Management"],
        "categories": ["Ancient", "Card Game"],
        "designers": ["Franz-Josef Lammers"],
        "artists": [],
        "publishers": ["Adlung-Spiele"],
    },
    162886: {
        "name": "Spirit Island",
        "name_zh": "靈語島",
        "description": "A cooperative game where spirits defend their island from colonizing invaders.",
        "description_zh": "合作遊戲，精靈保衛島嶼免受殖民者入侵。",
        "year_published": 2017,
        "min_players": 1,
        "max_players": 4,
        "playing_time": 120,
        "min_age": 13,
        "bgg_rating": 8.31,
        "rank": 5,
        "mechanics": ["Action Points", "Cooperative Play", "Variable Player Powers"],
        "categories": ["Environmental", "Fighting", "Mythology"],
        "designers": ["R. Eric Reuss"],
        "artists": [],
        "publishers": ["FFG"],
    },
    163390: {
        "name": "A Feast for Odin",
        "name_zh": "奧丁的盛宴",
        "description": "A complex worker-placement game of Viking exploration, farming, and raiding.",
        "description_zh": "維京人探索、農作與劫掠的複雜工人放置遊戲。",
        "year_published": 2016,
        "min_players": 1,
        "max_players": 4,
        "playing_time": 120,
        "min_age": 12,
        "bgg_rating": 7.91,
        "rank": 22,
        "mechanics": ["Worker Placement", "Tile Placement", "Action Points"],
        "categories": ["Economic", "Farming"],
        "designers": ["Uwe Rosenberg"],
        "artists": ["Dennis Lohausen"],
        "publishers": ["Lookout Games", "Z-Man Games"],
    },
    163412: {
        "name": "Patchwork",
        "name_zh": "拼布對決",
        "description": "A two-player tile-placement game where players create a quilt from fabric patches.",
        "description_zh": "雙人板塊放置遊戲，玩家用布料補丁創作拼布。",
        "year_published": 2014,
        "min_players": 2,
        "max_players": 2,
        "playing_time": 30,
        "min_age": 8,
        "bgg_rating": 7.67,
        "rank": None,
        "mechanics": ["Tile Placement", "Economic"],
        "categories": ["Abstract Strategy"],
        "designers": ["Uwe Rosenberg"],
        "artists": ["Klemens Franz"],
        "publishers": ["Lookout Games"],
    },
    167791: {
        "name": "Terraforming Mars",
        "name_zh": "殖民火星",
        "description": "Players work as corporations to terraform Mars, raising temperature, oxygen, and ocean coverage.",
        "description_zh": "玩家扮演企業殖民火星，提升溫度、氧氣與海洋覆蓋率。",
        "year_published": 2016,
        "min_players": 1,
        "max_players": 5,
        "playing_time": 120,
        "min_age": 12,
        "bgg_rating": 8.33,
        "rank": 3,
        "mechanics": ["Card Drafting", "Tile Placement", "Variable Player Powers"],
        "categories": ["Economic", "Science Fiction", "Territory Building"],
        "designers": ["Jacob Jansson-Vesanen"],
        "artists": [],
        "publishers": ["Stronghold Games", "Intrigue Games"],
    },
    169786: {
        "name": "Scythe",
        "name_zh": "鐮刀戰爭",
        "description": "An alternate-history 1920s game of engine-building, area control, and mechs in Eastern Europe.",
        "description_zh": "架空1920年代的引擎構建、區域控制與機甲遊戲，設定於東歐。",
        "year_published": 2016,
        "min_players": 1,
        "max_players": 5,
        "playing_time": 115,
        "min_age": 14,
        "bgg_rating": 7.87,
        "rank": 24,
        "mechanics": ["Action Points", "Area Control", "Engine Building"],
        "categories": ["Economic", "Science Fiction", "Territory Building"],
        "designers": ["Jamey Stegmaier"],
        "artists": ["Jakub Różalski"],
        "publishers": ["Stonemaier Games"],
    },
    174430: {
        "name": "Gloomhaven",
        "name_zh": "幽港鎮",
        "description": "A massive cooperative campaign game of tactical combat in a dark fantasy world.",
        "description_zh": "大型合作戰役遊戲，在黑暗奇幻世界進行戰術戰鬥。",
        "year_published": 2017,
        "min_players": 1,
        "max_players": 4,
        "playing_time": 120,
        "min_age": 14,
        "bgg_rating": 8.63,
        "rank": 1,
        "mechanics": ["Action Points", "Cooperative Play", "Deck, Bag, and Pool Building", "Modular Board"],
        "categories": ["Adventure", "Dungeon Crawler", "Fantasy"],
        "designers": ["Isaac Childres"],
        "artists": ["Alexandr Elichev", "Alvaro Nebot"],
        "publishers": ["Cephalofair Games"],
    },
    175914: {
        "name": "Food Chain Magnate",
        "name_zh": "餐飲大亨",
        "description": "A ruthless economic game of building a fast food empire with marketing, hiring, and price wars.",
        "description_zh": "無情的經濟遊戲，建立速食帝國，涉及行銷、雇用與價格戰。",
        "year_published": 2015,
        "min_players": 2,
        "max_players": 5,
        "playing_time": 120,
        "min_age": 14,
        "bgg_rating": 7.72,
        "rank": None,
        "mechanics": ["Building", "Economic"],
        "categories": ["Economic"],
        "designers": ["Joris Wiersinga", "Jeroen Doumen"],
        "artists": [],
        "publishers": ["Splotter Spellen"],
    },
    178900: {
        "name": "Codenames",
        "name_zh": "間諜密碼",
        "description": "A social word game where spymasters give one-word clues to help their team find their agents.",
        "description_zh": "社交文字遊戲，情報大師用一個詞幫隊友找到自己的特工。",
        "year_published": 2015,
        "min_players": 4,
        "max_players": 8,
        "playing_time": 15,
        "min_age": 10,
        "bgg_rating": 7.81,
        "rank": 38,
        "mechanics": ["Deduction", "Partnerships"],
        "categories": ["Card Game", "Party Game", "Spy"],
        "designers": ["Vlaada Chvátil"],
        "artists": [],
        "publishers": ["Czech Games Edition"],
    },
    182028: {
        "name": "Through the Ages: A New Story of Civilization",
        "name_zh": "穿越時空：文明新篇",
        "description": "A card-driven civilization building game spanning from antiquity to the modern age.",
        "description_zh": "卡牌驅動的文明建設遊戲，跨越古代到現代。",
        "year_published": 2015,
        "min_players": 2,
        "max_players": 4,
        "playing_time": 120,
        "min_age": 14,
        "bgg_rating": 8.30,
        "rank": 7,
        "mechanics": ["Card Drafting", "Civilization Building"],
        "categories": ["Civilization", "Economic"],
        "designers": ["Vlaada Chvátil"],
        "artists": [],
        "publishers": ["CGE"],
    },
    183394: {
        "name": "Viticulture Essential Edition",
        "name_zh": "葡萄園",
        "description": "A worker-placement game about building a vineyard, planting vines, and making wine in Tuscany.",
        "description_zh": "工人放置遊戲，在托斯卡尼建造葡萄園、種植葡萄、釀酒。",
        "year_published": 2013,
        "min_players": 1,
        "max_players": 6,
        "playing_time": 90,
        "min_age": 13,
        "bgg_rating": 7.63,
        "rank": None,
        "mechanics": ["Worker Placement"],
        "categories": ["Economic", "Farming"],
        "designers": ["Jamey Stegmaier", "Alan Stone"],
        "artists": [],
        "publishers": ["Stonemaier Games"],
    },
    187745: {
        "name": "Star Wars: Rebellion",
        "name_zh": "星際大戰：叛軍",
        "description": "An epic two-player asymmetric game of the Galactic Civil War in the Star Wars universe.",
        "description_zh": "星際大戰宇宙中銀河內戰的史詩級雙人非對稱遊戲。",
        "year_published": 2016,
        "min_players": 2,
        "max_players": 4,
        "playing_time": 240,
        "min_age": 14,
        "bgg_rating": 7.96,
        "rank": 28,
        "mechanics": ["Action Points", "Area Control", "Hidden Movement", "Variable Player Powers"],
        "categories": ["Fighting", "Miniatures", "Science Fiction"],
        "designers": ["Corey Konieczka"],
        "artists": [],
        "publishers": ["FFG"],
    },
    199792: {
        "name": "Everdell",
        "name_zh": "永綠谷",
        "description": "A worker-placement and engine-building game set in a charming woodland animal city.",
        "description_zh": "在迷人森林動物城鎮中的工人放置與引擎構建遊戲。",
        "year_published": 2018,
        "min_players": 1,
        "max_players": 4,
        "playing_time": 80,
        "min_age": 13,
        "bgg_rating": 7.69,
        "rank": None,
        "mechanics": ["Worker Placement", "Engine Building", "Set Collection"],
        "categories": ["Animals", "City Building", "Fantasy"],
        "designers": ["James A. Wilson"],
        "artists": [],
        "publishers": ["Tabletop Tycoon"],
    },
    201808: {
        "name": "Clank!",
        "name_zh": "鏗鏘",
        "description": "A deck-building dungeon crawl game where players explore a dragon's lair to steal artifacts.",
        "description_zh": "牌組構築地牢探索遊戲，玩家進入巨龍巢穴偷取神器。",
        "year_published": 2016,
        "min_players": 2,
        "max_players": 4,
        "playing_time": 60,
        "min_age": 13,
        "bgg_rating": 7.56,
        "rank": None,
        "mechanics": ["Deck, Bag, and Pool Building", "Map Deformation"],
        "categories": ["Adventure", "Dungeon Crawler", "Fantasy"],
        "designers": ["Paul Dennen"],
        "artists": [],
        "publishers": ["Renegade Game Studios"],
    },
    205059: {
        "name": "Arkham Horror: The Card Game",
        "name_zh": "阿卡姆驚魂卡牌版",
        "description": "A cooperative living card game of mystery, investigation, and cosmic horror in the Cthulhu Mythos.",
        "description_zh": "克蘇魯神話中的合作式卡牌遊戲，充滿謎團、調查與宇宙恐怖。",
        "year_published": 2016,
        "min_players": 1,
        "max_players": 4,
        "playing_time": 120,
        "min_age": 14,
        "bgg_rating": 8.15,
        "rank": 11,
        "mechanics": ["Cooperative Play", "Deck, Bag, and Pool Building", "Action Points"],
        "categories": ["Adventure", "Card Game", "Horror"],
        "designers": ["Nate French", "Matthew Newman"],
        "artists": [],
        "publishers": ["FFG"],
    },
    205459: {
        "name": "Arkham Horror: The Card Game",
        "name_zh": "阿卡姆驚魂卡牌版",
        "description": "A cooperative living card game of mystery, investigation, and cosmic horror.",
        "description_zh": "合作式卡牌遊戲，充滿謎團、調查與宇宙恐怖。",
        "year_published": 2016,
        "min_players": 1,
        "max_players": 4,
        "playing_time": 120,
        "min_age": 14,
        "bgg_rating": 8.15,
        "rank": 11,
        "mechanics": ["Cooperative Play", "Deck, Bag, and Pool Building"],
        "categories": ["Adventure", "Card Game", "Horror"],
        "designers": ["Nate French", "Matthew Newman"],
        "artists": [],
        "publishers": ["FFG"],
    },
    224517: {
        "name": "Brass: Birmingham",
        "name_zh": "黃銅：伯明翰",
        "description": "An economic strategy game of building industries and canals in industrial revolution England.",
        "description_zh": "在工業革命英格蘭建造產業與運河的經濟策略遊戲。",
        "year_published": 2018,
        "min_players": 2,
        "max_players": 4,
        "playing_time": 120,
        "min_age": 14,
        "bgg_rating": 8.54,
        "rank": 2,
        "mechanics": ["Hand Management", "Network Building", "Route/Network Building"],
        "categories": ["Economic", "Industry"],
        "designers": ["Martin Wallace", "Rox Games"],
        "artists": [],
        "publishers": ["Roxley", "Treefrog Games"],
    },
    230802: {
        "name": "Azul",
        "name_zh": "花磚物語",
        "description": "A beautiful tile-drafting game where players decorate the walls of the Royal Palace of Evora.",
        "description_zh": "精美的選磚遊戲，玩家裝飾埃武拉皇宮的牆壁。",
        "year_published": 2017,
        "min_players": 2,
        "max_players": 4,
        "playing_time": 40,
        "min_age": 8,
        "bgg_rating": 7.68,
        "rank": 100,
        "mechanics": ["Pattern Building", "Set Collection", "Tile Placement"],
        "categories": ["Abstract Strategy", "Puzzle"],
        "designers": ["Michael Kiesling"],
        "artists": ["Chris Quilliams"],
        "publishers": ["Plan B Games", "Next Move"],
    },
    233078: {
        "name": "Twilight Imperium: Fourth Edition",
        "name_zh": "暮光帝國四版",
        "description": "An epic 4X space game of galactic conquest, politics, trade, and technology.",
        "description_zh": "銀河征服、政治、貿易與科技的史詩級4X太空遊戲。",
        "year_published": 2017,
        "min_players": 3,
        "max_players": 8,
        "playing_time": 480,
        "min_age": 14,
        "bgg_rating": 8.37,
        "rank": None,
        "mechanics": ["Action Points", "Area Control", "Bidding", "Variable Player Powers"],
        "categories": ["Civilization", "Science Fiction", "Space Exploration"],
        "designers": ["Corey Konieczka", "Christian T. Petersen"],
        "artists": [],
        "publishers": ["FFG"],
    },
    237182: {
        "name": "Root",
        "name_zh": "根源之林",
        "description": "An asymmetric war game where different woodland factions compete for control of the forest.",
        "description_zh": "非對稱戰爭遊戲，不同森林派系競爭森林控制權。",
        "year_published": 2018,
        "min_players": 2,
        "max_players": 4,
        "playing_time": 90,
        "min_age": 10,
        "bgg_rating": 7.84,
        "rank": 30,
        "mechanics": ["Area Control", "Variable Player Powers", "Action Points"],
        "categories": ["Animals", "Fighting", "Political"],
        "designers": ["Cole Wehrle"],
        "artists": ["Kyle Ferrin"],
        "publishers": ["Leder Games"],
    },
    255984: {
        "name": "The Castles of Burgundy",
        "name_zh": "勃根地城堡",
        "description": "A dice-driven tile-placement game of building a medieval estate in the Burgundy region.",
        "description_zh": "擲骰驅動的板塊放置遊戲，在勃根地建造中世紀莊園。",
        "year_published": 2011,
        "min_players": 2,
        "max_players": 4,
        "playing_time": 90,
        "min_age": 12,
        "bgg_rating": 7.93,
        "rank": 23,
        "mechanics": ["Dice Rolling", "Tile Placement", "Set Collection"],
        "categories": ["Economic", "Medieval", "Territory Building"],
        "designers": ["Stefan Feld"],
        "artists": [],
        "publishers": ["Alea", "Ravensburger", "Rio Grande Games"],
    },
    266192: {
        "name": "Wingspan",
        "name_zh": "展翅翱翔",
        "description": "A competitive engine-building game about attracting birds to your wildlife preserve.",
        "description_zh": "競爭性引擎構建遊戲，吸引鳥類到您的野生保護區。",
        "year_published": 2019,
        "min_players": 1,
        "max_players": 5,
        "playing_time": 70,
        "min_age": 10,
        "bgg_rating": 8.09,
        "rank": 15,
        "mechanics": ["Engine Building", "Set Collection", "Card Drafting"],
        "categories": ["Animals", "Card Game"],
        "designers": ["Elizabeth Hargrave"],
        "artists": ["Natalia Rojas Castro", "Ana Maria Martinez Jaramillo", "Beth Sobel"],
        "publishers": ["Stonemaier Games"],
    },
    284083: {
        "name": "The Crew: The Quest for Planet Nine",
        "name_zh": "太空任務",
        "description": "A cooperative trick-taking card game about a space mission to find Planet Nine.",
        "description_zh": "合作吃墩紙牌遊戲，執行太空任務尋找第九行星。",
        "year_published": 2019,
        "min_players": 2,
        "max_players": 5,
        "playing_time": 20,
        "min_age": 10,
        "bgg_rating": 7.60,
        "rank": None,
        "mechanics": ["Cooperative Play", "Trick-taking", "Communication Limits"],
        "categories": ["Card Game", "Space Exploration"],
        "designers": ["Thomas Sing"],
        "artists": [],
        "publishers": ["Kosmos"],
    },
    2912: {
        "name": "Mr. Jack",
        "name_zh": "傑克先生",
        "description": "A two-player deduction game where one player is Jack the Ripper trying to escape.",
        "description_zh": "雙人推理遊戲，一名玩家是試圖逃脫的開膛手傑克。",
        "year_published": 2006,
        "min_players": 2,
        "max_players": 2,
        "playing_time": 30,
        "min_age": 9,
        "bgg_rating": 6.87,
        "rank": None,
        "mechanics": ["Deduction", "Variable Player Powers"],
        "categories": ["Deduction", "Murder/Mystery"],
        "designers": ["Bruno Cathala", "Ludovic Maublanc"],
        "artists": [],
        "publishers": ["Hurrican", "Iello"],
    },
    3077: {
        "name": "Stone Age",
        "name_zh": "石器時代",
        "description": "A worker-placement game of resource gathering, building, and civilization development in the Stone Age.",
        "description_zh": "石器時代的工人放置遊戲，涉及資源採集、建設與文明發展。",
        "year_published": 2008,
        "min_players": 2,
        "max_players": 4,
        "playing_time": 90,
        "min_age": 10,
        "bgg_rating": 7.14,
        "rank": None,
        "mechanics": ["Dice Rolling", "Set Collection", "Worker Placement"],
        "categories": ["Prehistoric", "Economic"],
        "designers": ["Bernd Brunnhofer"],
        "artists": [],
        "publishers": ["Hans im Glück", "Rio Grande Games", "Z-Man Games"],
    },
    342942: {
        "name": "Dune: Imperium",
        "name_zh": "沙丘：帝國",
        "description": "A deck-building and worker-placement game set in the Dune universe, blending combat and politics.",
        "description_zh": "沙丘宇宙中的牌組構築與工人放置遊戲，融合戰鬥與政治。",
        "year_published": 2020,
        "min_players": 1,
        "max_players": 4,
        "playing_time": 120,
        "min_age": 14,
        "bgg_rating": 8.17,
        "rank": 10,
        "mechanics": ["Deck, Bag, and Pool Building", "Worker Placement"],
        "categories": ["Science Fiction", "Fighting", "Political"],
        "designers": ["Paul Dennen"],
        "artists": [],
        "publishers": ["Dire Wolf"],
    },
}
