from datetime import datetime, timezone
from app.core.database import mongo_db

EXTRA_GAMES = [
    {"bgg_id": 167791, "name_en": "Terraforming Mars", "name_zh": "改造火星", "description_en": "In Terraforming Mars, you play one of those corporations and work together to raise the temperature, the oxygen level, and the ocean coverage until the environment is habitable.", "description_zh": "在改造火星中，你扮演一間企業，共同努力提升溫度、氧氣水平和海洋覆蓋率，直到環境適合居住。", "bgg_rating": 8.38, "bgg_rank": 5, "bgg_weight": 3.24, "min_players": 1, "max_players": 5, "min_playtime": 120, "max_playtime": 180, "min_age": 12, "year_published": 2016, "users_rated": 48000, "categories": [{"id": 0, "name": "Science Fiction"}, {"id": 1, "name": "Economic"}], "mechanics": [{"id": 0, "name": "Card Drafting"}, {"id": 1, "name": "Engine Building"}, {"id": 2, "name": "Tile Placement"}], "designers": ["Jacob Fryxelius"], "publishers": ["Stronghold Games"]},
    {"bgg_id": 220308, "name_en": "Gaia Project", "name_zh": "蓋亞計畫", "description_en": "Gaia Project is a terraforming game in which you strive to transform planets into your faction's home turf.", "description_zh": "蓋亞計畫是一款地形改造遊戲，你努力將行星轉化為你陣營的主場。", "bgg_rating": 8.36, "bgg_rank": 6, "bgg_weight": 4.06, "min_players": 2, "max_players": 4, "min_playtime": 60, "max_playtime": 150, "min_age": 12, "year_published": 2017, "users_rated": 16000, "categories": [{"id": 0, "name": "Science Fiction"}, {"id": 1, "name": "Territory Building"}], "mechanics": [{"id": 0, "name": "Hex-and-Counter"}, {"id": 1, "name": "Tech Trees"}], "designers": ["Jens Drögemüller"], "publishers": [" Feuerland Spiele"]},
    {"bgg_id": 237182, "name_en": "Root", "name_zh": "根源", "description_en": "Root is a game of woodland might and right. Players take on the roles of different factions, each with unique abilities and victory conditions.", "description_zh": "根源是一款森林權力與正義的遊戲。玩家扮演不同派系，各自擁有獨特能力和勝利條件。", "bgg_rating": 8.12, "bgg_rank": 25, "bgg_weight": 3.74, "min_players": 2, "max_players": 4, "min_playtime": 60, "max_playtime": 90, "min_age": 10, "year_published": 2018, "users_rated": 22000, "categories": [{"id": 0, "name": "Animals"}, {"id": 1, "name": "Medieval"}], "mechanics": [{"id": 0, "name": "Area Control"}, {"id": 1, "name": "Variable Player Powers"}, {"id": 2, "name": "Action Points"}], "designers": ["Cole Wehrle"], "publishers": ["Leder Games"]},
    {"bgg_id": 169786, "name_en": "Scythe", "name_zh": "鐮刀戰爭", "description_en": "Scythe is an engine-building game set in an alternate-history 1920s period. It is a time of farming and war, broken hearts and rusted gears.", "description_zh": "鐮刀戰爭是一款引擎構建遊戲，背景設定在另一個歷史的1920年代。這是一個農耕與戰爭的時代。", "bgg_rating": 8.04, "bgg_rank": 18, "bgg_weight": 3.44, "min_players": 1, "max_players": 5, "min_playtime": 90, "max_playtime": 115, "min_age": 14, "year_published": 2016, "users_rated": 36000, "categories": [{"id": 0, "name": "Economic"}, {"id": 1, "name": "Science Fiction"}], "mechanics": [{"id": 0, "name": "Engine Building"}, {"id": 1, "name": "Area Control"}, {"id": 2, "name": "Hex-and-Counter"}], "designers": ["Jamey Stegmaier"], "publishers": ["Stonemaier Games"]},
    {"bgg_id": 187645, "name_en": "Spirit Island", "name_zh": "靈魂島", "description_en": "Spirit Island is a cooperative game where players take the roles of different spirits to defend their island home from colonizing invaders.", "description_zh": "靈魂島是一款合作遊戲，玩家扮演不同靈魂，保衛他們的島嶼家園免受殖民者入侵。", "bgg_rating": 8.30, "bgg_rank": 8, "bgg_weight": 3.78, "min_players": 1, "max_players": 4, "min_playtime": 90, "max_playtime": 120, "min_age": 13, "year_published": 2017, "users_rated": 18000, "categories": [{"id": 0, "name": "Cooperative"}, {"id": 1, "name": "Fantasy"}], "mechanics": [{"id": 0, "name": "Cooperative"}, {"id": 1, "name": "Variable Player Powers"}, {"id": 2, "name": "Area Control"}], "designers": ["R. Eric Reuss"], "publishers": ["Greater Than Games"]},
    {"bgg_id": 205637, "name_en": "Agricola", "name_zh": "農家樂", "description_en": "In Agricola, you're a farmer in a wooden shack with your spouse and little else. You must grow your farm and feed your family.", "description_zh": "在農家樂中，你是一個住在木屋裡的農夫，與配偶一起從無到有地建立農場並養家糊口。", "bgg_rating": 7.94, "bgg_rank": 35, "bgg_weight": 3.64, "min_players": 1, "max_players": 5, "min_playtime": 30, "max_playtime": 150, "min_age": 12, "year_published": 2007, "users_rated": 38000, "categories": [{"id": 0, "name": "Farming"}, {"id": 1, "name": "Economic"}], "mechanics": [{"id": 0, "name": "Worker Placement"}, {"id": 1, "name": "Hand Management"}, {"id": 2, "name": "Drafting"}], "designers": ["Uwe Rosenberg"], "publishers": ["Lookout Games"]},
    {"bgg_id": 28720, "name_en": "Brass: Lancashire", "name_zh": "黃銅：蘭開夏", "description_en": "Brass: Lancashire tells the story of the cotton industry in Lancashire during the Industrial Revolution.", "description_zh": "黃銅：蘭開夏講述了工業革命時期蘭開夏棉紡織業的故事。", "bgg_rating": 8.22, "bgg_rank": 10, "bgg_weight": 3.84, "min_players": 2, "max_players": 4, "min_playtime": 60, "max_playtime": 120, "min_age": 14, "year_published": 2007, "users_rated": 18000, "categories": [{"id": 0, "name": "Economic"}, {"id": 1, "name": "Industry"}], "mechanics": [{"id": 0, "name": "Hand Management"}, {"id": 1, "name": "Network Building"}], "designers": ["Martin Wallace"], "publishers": ["Roxley Games"]},
    {"bgg_id": 198928, "name_en": "A Feast for Odin", "name_zh": "奧丁的盛宴", "description_en": "A Feast for Odin is a saga in the form of a board game. You are reliving the cultural achievements, mercantile expeditions, and pillages of those tribes.", "description_zh": "奧丁的盛宴是以桌遊形式呈現的傳奇故事。你重新體驗維京部落的文化成就、商業遠征和劫掠。", "bgg_rating": 7.89, "bgg_rank": 40, "bgg_weight": 3.58, "min_players": 1, "max_players": 4, "min_playtime": 30, "max_playtime": 120, "min_age": 12, "year_published": 2016, "users_rated": 14000, "categories": [{"id": 0, "name": "Economic"}, {"id": 1, "name": "Medieval"}], "mechanics": [{"id": 0, "name": "Worker Placement"}, {"id": 1, "name": "Tile Placement"}], "designers": ["Uwe Rosenberg"], "publishers": ["Stronghold Games"]},
    {"bgg_id": 266810, "name_en": "Everdell", "name_zh": "永翠谷", "description_en": "Everdell is a streamlined worker placement game that features a detailed world through tableaux building and engaging critter themes.", "description_zh": "永翠谷是一款精簡的工人放置遊戲，具有細緻的世界觀和迷人的動物主題。", "bgg_rating": 7.88, "bgg_rank": 42, "bgg_weight": 2.78, "min_players": 1, "max_players": 4, "min_playtime": 40, "max_playtime": 80, "min_age": 10, "year_published": 2018, "users_rated": 16000, "categories": [{"id": 0, "name": "Animals"}, {"id": 1, "name": "City Building"}], "mechanics": [{"id": 0, "name": "Worker Placement"}, {"id": 1, "name": "Engine Building"}, {"id": 2, "name": "Set Collection"}], "designers": ["James A. Wilson"], "publishers": ["Tabletop Tycoon"]},
    {"bgg_id": 120677, "name_en": "War of the Ring (Second Edition)", "name_zh": "魔戒聖戰（二版）", "description_en": "War of the Ring is a grand strategy board game that allows players to immerse themselves in J.R.R. Tolkien's Middle-earth.", "description_zh": "魔戒聖戰是一款大型策略桌遊，讓玩家沉浸在托爾金的中土世界之中。", "bgg_rating": 8.34, "bgg_rank": 7, "bgg_weight": 4.30, "min_players": 2, "max_players": 4, "min_playtime": 120, "max_playtime": 240, "min_age": 13, "year_published": 2011, "users_rated": 10000, "categories": [{"id": 0, "name": "Fantasy"}, {"id": 1, "name": "Fighting"}], "mechanics": [{"id": 0, "name": "Area Control"}, {"id": 1, "name": "Dice Rolling"}, {"id": 2, "name": "Variable Player Powers"}], "designers": ["Roberto Di Meglio"], "publishers": ["Ares Games"]},
    {"bgg_id": 35424, "name_en": "Eclipse: New Dawn for the Galaxy", "name_zh": "日蝕：銀河新黎明", "description_en": "Eclipse is a 4X game where players explore, expand, exploit, and exterminate in a galaxy of interstellar empires.", "description_zh": "日蝕是一款4X遊戲，玩家在星際帝國的銀河中探索、擴張、開發和消滅。", "bgg_rating": 7.87, "bgg_rank": 45, "bgg_weight": 3.64, "min_players": 2, "max_players": 6, "min_playtime": 60, "max_playtime": 200, "min_age": 14, "year_published": 2011, "users_rated": 18000, "categories": [{"id": 0, "name": "Science Fiction"}, {"id": 1, "name": "Civilization"}], "mechanics": [{"id": 0, "name": "Hex-and-Counter"}, {"id": 1, "name": "Dice Rolling"}, {"id": 2, "name": "Tech Trees"}], "designers": ["Touko Tahkokorpi"], "publishers": ["Lautapelit.fi"]},
    {"bgg_id": 102794, "name_en": "Cavern Tavern", "name_zh": "洞穴酒館", "description_en": "In Cavern Tavern, you are a worker at a tavern and must serve drinks, manage the bar, and keep the patrons happy.", "description_zh": "在洞穴酒館中，你是酒館的員工，必須提供飲料、管理吧台並讓顧客滿意。", "bgg_rating": 7.20, "bgg_rank": 350, "bgg_weight": 2.50, "min_players": 2, "max_players": 4, "min_playtime": 30, "max_playtime": 60, "min_age": 10, "year_published": 2015, "users_rated": 5000, "categories": [{"id": 0, "name": "Fantasy"}, {"id": 1, "name": "Medieval"}], "mechanics": [{"id": 0, "name": "Worker Placement"}, {"id": 1, "name": "Set Collection"}], "designers": ["Tony Boyd"], "publishers": ["Final Frontier Games"]},
    {"bgg_id": 176494, "name_en": "Viticulture Essential Edition", "name_zh": "釀酒世家：精華版", "description_en": "Viticulture is a worker-placement game where you find yourself in the roles of winemakers in pre-modern Tuscany.", "description_zh": "釀酒世家是一款工人放置遊戲，你扮演現代早期托斯卡尼的釀酒師。", "bgg_rating": 7.88, "bgg_rank": 44, "bgg_weight": 2.88, "min_players": 1, "max_players": 6, "min_playtime": 45, "max_playtime": 90, "min_age": 13, "year_published": 2013, "users_rated": 18000, "categories": [{"id": 0, "name": "Farming"}, {"id": 1, "name": "Economic"}], "mechanics": [{"id": 0, "name": "Worker Placement"}, {"id": 1, "name": "Hand Management"}], "designers": ["Jamey Stegmaier"], "publishers": ["Stonemaier Games"]},
    {"bgg_id": 261357, "name_en": "Dinosaur Island", "name_zh": "恐龍島", "description_en": "In Dinosaur Island, players collect DNA, research DNA sequences, and build dinosaurs to create the most exciting dinosaur theme park.", "description_zh": "在恐龍島中，玩家收集DNA、研究DNA序列，建造恐龍來打造最刺激的恐龍主題公園。", "bgg_rating": 7.20, "bgg_rank": 400, "bgg_weight": 2.60, "min_players": 2, "max_players": 4, "min_playtime": 60, "max_playtime": 120, "min_age": 10, "year_published": 2018, "users_rated": 7000, "categories": [{"id": 0, "name": "Economic"}, {"id": 1, "name": "Prehistoric"}], "mechanics": [{"id": 0, "name": "Worker Placement"}, {"id": 1, "name": "Set Collection"}, {"id": 2, "name": "Dice Rolling"}], "designers": ["Jonathan Gilmour"], "publishers": ["Pandasaurus Games"]},
    {"bgg_id": 224536, "name_en": "Rising Sun", "name_zh": "旭日東升", "description_en": "Rising Sun is a board game about political alliances, betrayal, and warfare in feudal Japan.", "description_zh": "旭日東升是一款關於封建日本政治聯盟、背叛和戰爭的桌遊。", "bgg_rating": 7.60, "bgg_rank": 150, "bgg_weight": 3.12, "min_players": 3, "max_players": 5, "min_playtime": 90, "max_playtime": 120, "min_age": 14, "year_published": 2018, "users_rated": 14000, "categories": [{"id": 0, "name": "Fighting"}, {"id": 1, "name": "Medieval"}], "mechanics": [{"id": 0, "name": "Area Control"}, {"id": 1, "name": "Negotiation"}, {"id": 2, "name": "Variable Player Powers"}], "designers": ["Eric M. Lang"], "publishers": ["CMON"]},
    {"bgg_id": 171, "name_en": "Chess", "name_zh": "西洋棋", "description_en": "Chess is a two-player strategy board game played on a checkered board with 64 squares arranged in an 8×8 grid.", "description_zh": "西洋棋是一種兩人對弈的策略棋盤遊戲，在8×8方格棋盤上進行。", "bgg_rating": 6.90, "bgg_rank": 800, "bgg_weight": 3.70, "min_players": 2, "max_players": 2, "min_playtime": 30, "max_playtime": 60, "min_age": 6, "year_published": -500, "users_rated": 15000, "categories": [{"id": 0, "name": "Abstract"}, {"id": 1, "name": "Strategy"}], "mechanics": [{"id": 0, "name": "Grid Movement"}, {"id": 1, "name": "Variable Player Powers"}], "designers": [], "publishers": []},
    {"bgg_id": 193738, "name_en": "Patchwork", "name_zh": "拼布藝術", "description_en": "Patchwork is a two-player game where players compete to build the most aesthetic and highest-scoring patchwork quilt.", "description_zh": "拼布藝術是一款兩人遊戲，玩家競爭建造最具美感且得分最高的拼布被子。", "bgg_rating": 7.68, "bgg_rank": 120, "bgg_weight": 1.76, "min_players": 2, "max_players": 2, "min_playtime": 15, "max_playtime": 30, "min_age": 8, "year_published": 2014, "users_rated": 24000, "categories": [{"id": 0, "name": "Puzzle"}, {"id": 1, "name": "Economic"}], "mechanics": [{"id": 0, "name": "Tile Placement"}, {"id": 1, "name": "Time Track"}], "designers": ["Uwe Rosenberg"], "publishers": ["Lookout Games"]},
    {"bgg_id": 204052, "name_en": "Azul", "name_zh": "花磚物語", "description_en": "Azul is a tile-placement game in which players compete for the best score by claiming tiles and arranging them on their board.", "description_zh": "花磚物語是一款板塊放置遊戲，玩家通過獲取板塊並在棋盤上排列來爭取最高分數。", "bgg_rating": 7.56, "bgg_rank": 130, "bgg_weight": 1.78, "min_players": 2, "max_players": 4, "min_playtime": 30, "max_playtime": 45, "min_age": 8, "year_published": 2017, "users_rated": 32000, "categories": [{"id": 0, "name": "Abstract"}, {"id": 1, "name": "Puzzle"}], "mechanics": [{"id": 0, "name": "Tile Placement"}, {"id": 1, "name": "Set Collection"}], "designers": ["Michael Kiesling"], "publishers": ["Plan B Games"]},
    {"bgg_id": 244521, "name_en": "Clank! A Deck-Building Adventure", "name_zh": "噠噠！牌組構建冒險", "description_en": "Clank! is a deck-building game where players descend into the dungeon to collect artifacts and escape before the dragon catches them.", "description_zh": "噠噠！是一款牌組構建遊戲，玩家潛入地下城收集神器，並在龍抓住他們之前逃脫。", "bgg_rating": 7.52, "bgg_rank": 140, "bgg_weight": 2.24, "min_players": 2, "max_players": 4, "min_playtime": 30, "max_playtime": 60, "min_age": 10, "year_published": 2016, "users_rated": 18000, "categories": [{"id": 0, "name": "Adventure"}, {"id": 1, "name": "Fantasy"}], "mechanics": [{"id": 0, "name": "Deck Building"}, {"id": 1, "name": "Map Addition"}, {"id": 2, "name": "Push Your Luck"}], "designers": ["Paul Dennen"], "publishers": ["Renegade Game Studios"]},
    {"bgg_id": 178900, "name_en": "Codenames", "name_zh": "代號密碼", "description_en": "Codenames is a social word game where two rival spymasters know the secret identities of 25 agents.", "description_zh": "代號密碼是一款社交文字遊戲，兩位對抗的間諜頭目知道25位特工的秘密身分。", "bgg_rating": 7.82, "bgg_rank": 55, "bgg_weight": 1.30, "min_players": 4, "max_players": 8, "min_playtime": 15, "max_playtime": 30, "min_age": 10, "year_published": 2015, "users_rated": 45000, "categories": [{"id": 0, "name": "Party"}, {"id": 1, "name": "Spies/Secret Agents"}], "mechanics": [{"id": 0, "name": "Communication Limits"}, {"id": 1, "name": "Team-Based Game"}], "designers": ["Vlaada Chvátil"], "publishers": ["Czech Games Edition"]},
    {"bgg_id": 252447, "name_en": "The Quacks of Quedlinburg", "name_zh": "奎德林堡的江湖醫生", "description_en": "The Quacks of Quedlinburg is a strategic push-your-luck game in which you draw ingredient chips from a bag to brew potions.", "description_zh": "奎德林堡的江湖醫生是一款策略型博運氣遊戲，你從袋子中抽取配料籌碼來釀製藥水。", "bgg_rating": 7.62, "bgg_rank": 110, "bgg_weight": 2.08, "min_players": 2, "max_players": 4, "min_playtime": 30, "max_playtime": 45, "min_age": 10, "year_published": 2018, "users_rated": 18000, "categories": [{"id": 0, "name": "Medical"}, {"id": 1, "name": "Humor"}], "mechanics": [{"id": 0, "name": "Push Your Luck"}, {"id": 1, "name": "Bag Building"}, {"id": 2, "name": "Set Collection"}], "designers": ["Wolfgang Warsch"], "publishers": ["Schmidt Spiele"]},
    {"bgg_id": 223029, "name_en": "The Mind", "name_zh": "心靈同步", "description_en": "The Mind is a cooperative card game where players must play cards in ascending order without communicating.", "description_zh": "心靈同步是一款合作卡牌遊戲，玩家必須在不溝通的情況下按升序出牌。", "bgg_rating": 7.12, "bgg_rank": 450, "bgg_weight": 1.20, "min_players": 2, "max_players": 4, "min_playtime": 10, "max_playtime": 20, "min_age": 8, "year_published": 2018, "users_rated": 20000, "categories": [{"id": 0, "name": "Party"}, {"id": 1, "name": "Card Game"}], "mechanics": [{"id": 0, "name": "Cooperative"}, {"id": 1, "name": "Communication Limits"}], "designers": ["Wolfgang Warsch"], "publishers": ["Nürnberger-Spielkarten"]},
    {"bgg_id": 203416, "name_en": "Photosynthesis", "name_zh": "光合作用", "description_en": "Photosynthesis is a strategy game where players plant trees and harness the power of the sun to grow their forest.", "description_zh": "光合作用是一款策略遊戲，玩家種植樹木並利用陽光的力量來生長他們的森林。", "bgg_rating": 7.12, "bgg_rank": 460, "bgg_weight": 2.32, "min_players": 2, "max_players": 4, "min_playtime": 30, "max_playtime": 60, "min_age": 8, "year_published": 2017, "users_rated": 18000, "categories": [{"id": 0, "name": "Animals"}, {"id": 1, "name": "Nature"}], "mechanics": [{"id": 0, "name": "Tile Placement"}, {"id": 1, "name": "Area Control"}], "designers": ["Hjalmar Hach"], "publishers": ["Blue Orange Games"]},
    {"bgg_id": 181304, "name_en": "Betrayal at House on the Hill", "name_zh": "山間鬼屋的背叛", "description_en": "Betrayal at House on the Hill is a tile game where one player betrays the others in a haunted house.", "description_zh": "山間鬼屋的背叛是一款板塊遊戲，其中一名玩家在鬼屋中背叛其他玩家。", "bgg_rating": 6.92, "bgg_rank": 700, "bgg_weight": 2.06, "min_players": 3, "max_players": 6, "min_playtime": 60, "max_playtime": 60, "min_age": 12, "year_published": 2004, "users_rated": 28000, "categories": [{"id": 0, "name": "Horror"}, {"id": 1, "name": "Exploration"}], "mechanics": [{"id": 0, "name": "Cooperative"}, {"id": 1, "name": "Variable Player Powers"}, {"id": 2, "name": "Modular Board"}], "designers": ["Bruce Glassco"], "publishers": ["Avalon Hill"]},
    {"bgg_id": 246732, "name_en": "Century: Spice Road", "name_zh": "世紀：香料之路", "description_en": "Century: Spice Road is an engine-building game where players collect spices and trade them for points.", "description_zh": "世紀：香料之路是一款引擎構建遊戲，玩家收集香料並交易換取分數。", "bgg_rating": 7.28, "bgg_rank": 300, "bgg_weight": 1.70, "min_players": 2, "max_players": 5, "min_playtime": 30, "max_playtime": 45, "min_age": 8, "year_published": 2017, "users_rated": 16000, "categories": [{"id": 0, "name": "Economic"}, {"id": 1, "name": "Medieval"}], "mechanics": [{"id": 0, "name": "Engine Building"}, {"id": 1, "name": "Card Drafting"}, {"id": 2, "name": "Set Collection"}], "designers": ["Emerson Matsuuchi"], "publishers": ["Plan B Games"]},
    {"bgg_id": 236374, "name_en": "Sagrada", "name_zh": "聖家堂", "description_en": "Sagrada is a dice-drafting game where players build stained glass windows using colorful dice.", "description_zh": "聖家堂是一款骰子輪抽遊戲，玩家使用彩色骰子建造彩色玻璃窗。", "bgg_rating": 7.24, "bgg_rank": 320, "bgg_weight": 1.80, "min_players": 1, "max_players": 4, "min_playtime": 20, "max_playtime": 40, "min_age": 10, "year_published": 2017, "users_rated": 17000, "categories": [{"id": 0, "name": "Puzzle"}, {"id": 1, "name": "Renaissance"}], "mechanics": [{"id": 0, "name": "Dice Rolling"}, {"id": 1, "name": "Card Drafting"}, {"id": 2, "name": "Set Collection"}], "designers": ["Adrian Adamescu"], "publishers": ["Floodgate Games"]},
    {"bgg_id": 291457, "name_en": "Maracaibo", "name_zh": "馬拉開波", "description_en": "Maracaibo is a strategy game set in the Caribbean where players sail, trade, and build their influence.", "description_zh": "馬拉開波是一款加勒比海策略遊戲，玩家航行、貿易並建立影響力。", "bgg_rating": 7.44, "bgg_rank": 200, "bgg_weight": 3.20, "min_players": 1, "max_players": 4, "min_playtime": 60, "max_playtime": 120, "min_age": 12, "year_published": 2019, "users_rated": 6000, "categories": [{"id": 0, "name": "Economic"}, {"id": 1, "name": "Nautical"}], "mechanics": [{"id": 0, "name": "Engine Building"}, {"id": 1, "name": "Deck Building"}, {"id": 2, "name": "Area Control"}], "designers": ["Alexander Pfister"], "publishers": ["Eagle-Gryphon Games"]},
    {"bgg_id": 250430, "name_en": "Great Western Trail", "name_zh": "大西部牛仔路", "description_en": "Great Western Trail is a game about driving cattle from Texas to Kansas City, building your herd and managing your ranch.", "description_zh": "大西部牛仔路是一款從德克薩斯趕牛到堪薩斯城的遊戲，建立牛群並管理牧場。", "bgg_rating": 8.02, "bgg_rank": 16, "bgg_weight": 3.50, "min_players": 2, "max_players": 4, "min_playtime": 75, "max_playtime": 150, "min_age": 12, "year_published": 2016, "users_rated": 14000, "categories": [{"id": 0, "name": "Economic"}, {"id": 1, "name": "Modern"}], "mechanics": [{"id": 0, "name": "Deck Building"}, {"id": 1, "name": "Worker Placement"}, {"id": 2, "name": "Point to Point Movement"}], "designers": ["Alexander Pfister"], "publishers": ["Eagle-Gryphon Games"]},
    {"bgg_id": 231392, "name_en": "Blood Rage", "name_zh": "血色狂怒", "description_en": "Blood Rage is a Viking board game where players control clans and fight for glory before Ragnarok destroys the world.", "description_zh": "血色狂怒是一款維京桌遊，玩家控制氏族，在世界末日毀滅世界之前為榮耀而戰。", "bgg_rating": 7.80, "bgg_rank": 60, "bgg_weight": 2.90, "min_players": 2, "max_players": 4, "min_playtime": 60, "max_playtime": 90, "min_age": 13, "year_published": 2015, "users_rated": 19000, "categories": [{"id": 0, "name": "Fighting"}, {"id": 1, "name": "Medieval"}], "mechanics": [{"id": 0, "name": "Card Drafting"}, {"id": 1, "name": "Area Control"}, {"id": 2, "name": "Variable Player Powers"}], "designers": ["Eric M. Lang"], "publishers": ["CMON"]},
    {"bgg_id": 17602, "name_en": "Power Grid", "name_zh": "電力公司", "description_en": "Power Grid is an economic game where players bid for power plants, buy resources, and build networks to power cities.", "description_zh": "電力公司是一款經濟遊戲，玩家競標發電廠、購買資源並建設網路為城市供電。", "bgg_rating": 7.68, "bgg_rank": 125, "bgg_weight": 3.40, "min_players": 2, "max_players": 6, "min_playtime": 120, "max_playtime": 120, "min_age": 12, "year_published": 2004, "users_rated": 28000, "categories": [{"id": 0, "name": "Economic"}, {"id": 1, "name": "Industry"}], "mechanics": [{"id": 0, "name": "Auction"}, {"id": 1, "name": "Network Building"}, {"id": 2, "name": "Route Building"}], "designers": ["Friedemann Friese"], "publishers": ["2F-Spiele"]},
    {"bgg_id": 31260, "name_en": "Agricola: All Creatures Big and Small", "name_zh": "農家樂：動物大集合", "description_en": "A simplified two-player version of Agricola focused on raising animals and building fences.", "description_zh": "農家樂的簡化雙人版，專注於飼養動物和建造圍欄。", "bgg_rating": 7.34, "bgg_rank": 270, "bgg_weight": 2.30, "min_players": 2, "max_players": 2, "min_playtime": 30, "max_playtime": 30, "min_age": 8, "year_published": 2012, "users_rated": 12000, "categories": [{"id": 0, "name": "Farming"}, {"id": 1, "name": "Animals"}], "mechanics": [{"id": 0, "name": "Worker Placement"}, {"id": 1, "name": "Tile Placement"}], "designers": ["Uwe Rosenberg"], "publishers": ["Lookout Games"]},
    {"bgg_id": 27872, "name_en": "Power Grid: Factory Manager", "name_zh": "電力公司：工廠經理", "description_en": "A standalone game where you manage a factory, buying machines and optimizing your production.", "description_zh": "一款獨立遊戲，你管理工廠、購買機器並優化生產。", "bgg_rating": 6.80, "bgg_rank": 900, "bgg_weight": 2.60, "min_players": 2, "max_players": 5, "min_playtime": 60, "max_playtime": 90, "min_age": 10, "year_published": 2008, "users_rated": 6000, "categories": [{"id": 0, "name": "Economic"}, {"id": 1, "name": "Industry"}], "mechanics": [{"id": 0, "name": "Auction"}, {"id": 1, "name": "Engine Building"}], "designers": ["Friedemann Friese"], "publishers": ["2F-Spiele"]},
    {"bgg_id": 432, "name_en": "Catan: Cities & Knights", "name_zh": "卡坦島：城市與騎士", "description_en": "Catan: Cities & Knights adds city improvements, knight tokens, and barbarian invasions to the base game.", "description_zh": "卡坦島：城市與騎士為基礎遊戲添加了城市升級、騎士標記和蠻族入侵。", "bgg_rating": 7.50, "bgg_rank": 160, "bgg_weight": 2.76, "min_players": 3, "max_players": 4, "min_playtime": 90, "max_playtime": 150, "min_age": 10, "year_published": 1998, "users_rated": 18000, "categories": [{"id": 0, "name": "Economic"}, {"id": 1, "name": "Medieval"}], "mechanics": [{"id": 0, "name": "Dice Rolling"}, {"id": 1, "name": "Trading"}, {"id": 2, "name": "Modular Board"}], "designers": ["Klaus Teuber"], "publishers": ["Kosmos"]},
    {"bgg_id": 6249, "name_en": "Battle Line", "name_zh": "戰線", "description_en": "Battle Line is a two-player card game about forming formations of troops to win flags on the battlefield.", "description_zh": "戰線是一款兩人卡牌遊戲，關於在戰場上編排部隊陣型來贏得旗幟。", "bgg_rating": 7.18, "bgg_rank": 500, "bgg_weight": 2.00, "min_players": 2, "max_players": 2, "min_playtime": 30, "max_playtime": 30, "min_age": 10, "year_published": 2000, "users_rated": 8000, "categories": [{"id": 0, "name": "Card Game"}, {"id": 1, "name": "Ancient"}], "mechanics": [{"id": 0, "name": "Hand Management"}, {"id": 1, "name": "Set Collection"}], "designers": ["Reiner Knizia"], "publishers": ["GMT Games"]},
    {"bgg_id": 164153, "name_en": " Istanbul", "name_zh": "伊斯坦堡", "description_en": "Istanbul is a board game where players move their merchant around the bazaar to collect rubies.", "description_zh": "伊斯坦堡是一款桌遊，玩家在集市中移動商人來收集紅寶石。", "bgg_rating": 7.46, "bgg_rank": 180, "bgg_weight": 2.52, "min_players": 2, "max_players": 5, "min_playtime": 40, "max_playtime": 60, "min_age": 10, "year_published": 2014, "users_rated": 12000, "categories": [{"id": 0, "name": "Economic"}, {"id": 1, "name": "Medieval"}], "mechanics": [{"id": 0, "name": "Worker Placement"}, {"id": 1, "name": "Set Collection"}, {"id": 2, "name": "Push Your Luck"}], "designers": ["Rüdiger Dorn"], "publishers": ["Alderac Entertainment Group"]},
    {"bgg_id": 217920, "name_en": "Machi Koro", "name_zh": "骰子街", "description_en": "Machi Koro is a fast-paced game where players roll dice, earn income, and build landmarks to complete their city.", "description_zh": "骰子街是一款快節奏遊戲，玩家擲骰賺取收入並建造地標來完成城市。", "bgg_rating": 6.82, "bgg_rank": 850, "bgg_weight": 1.50, "min_players": 2, "max_players": 4, "min_playtime": 20, "max_playtime": 30, "min_age": 8, "year_published": 2014, "users_rated": 18000, "categories": [{"id": 0, "name": "Economic"}, {"id": 1, "name": "City Building"}], "mechanics": [{"id": 0, "name": "Dice Rolling"}, {"id": 1, "name": "Engine Building"}, {"id": 2, "name": "Set Collection"}], "designers": ["Masato Suganuma"], "publishers": ["Pandasaurus Games"]},
    {"bgg_id": 21045, "name_en": "Hansa Teutonica", "name_zh": "漢薩同盟", "description_en": "Hansa Teutonica is a strategy game about merchants in the Hanseatic League establishing trade routes and offices.", "description_zh": "漢薩同盟是一款關於漢薩同盟商人的策略遊戲，建立貿易路線和辦事處。", "bgg_rating": 7.60, "bgg_rank": 145, "bgg_weight": 2.94, "min_players": 2, "max_players": 5, "min_playtime": 45, "max_playtime": 90, "min_age": 12, "year_published": 2009, "users_rated": 8000, "categories": [{"id": 0, "name": "Economic"}, {"id": 1, "name": "Medieval"}], "mechanics": [{"id": 0, "name": "Network Building"}, {"id": 1, "name": "Route Building"}, {"id": 2, "name": "Area Control"}], "designers": ["Andreas Steding"], "publishers": ["Factum Game"]},
    {"bgg_id": 265973, "name_en": "Underwater Cities", "name_zh": "水下城市", "description_en": "Underwater Cities is a worker placement game where players build underwater habitats and develop technologies.", "description_zh": "水下城市是一款工人放置遊戲，玩家建造水下棲息地並開發技術。", "bgg_rating": 7.74, "bgg_rank": 90, "bgg_weight": 3.14, "min_players": 1, "max_players": 4, "min_playtime": 60, "max_playtime": 120, "min_age": 12, "year_published": 2018, "users_rated": 7000, "categories": [{"id": 0, "name": "Science Fiction"}, {"id": 1, "name": "City Building"}], "mechanics": [{"id": 0, "name": "Worker Placement"}, {"id": 1, "name": "Hand Management"}, {"id": 2, "name": "Tech Trees"}], "designers": ["Vladimír Suchý"], "publishers": ["Deluxe"]},
    {"bgg_id": 224517, "name_en": "Twilight Struggle", "name_zh": "暮光博弈", "description_en": "Twilight Struggle is a two-player game simulating the Cold War between the US and USSR.", "description_zh": "暮光博弈是一款模擬美蘇冷戰的兩人遊戲。", "bgg_rating": 8.26, "bgg_rank": 9, "bgg_weight": 3.58, "min_players": 2, "max_players": 2, "min_playtime": 120, "max_playtime": 180, "min_age": 13, "year_published": 2005, "users_rated": 20000, "categories": [{"id": 0, "name": "Modern"}, {"id": 1, "name": "Political"}], "mechanics": [{"id": 0, "name": "Card Drafting"}, {"id": 1, "name": "Area Control"}, {"id": 2, "name": "Point to Point Movement"}], "designers": ["Ananda Gupta"], "publishers": ["GMT Games"]},
    {"bgg_id": 188332, "name_en": "The Castles of Mad King Ludwig", "name_zh": "瘋王路德維希的城堡", "description_en": "The Castles of Mad King Ludwig is a tile-laying game where players build castles room by room.", "description_zh": "瘋王路德維希的城堡是一款板塊放置遊戲，玩家逐房建造城堡。", "bgg_rating": 7.48, "bgg_rank": 170, "bgg_weight": 2.62, "min_players": 1, "max_players": 4, "min_playtime": 60, "max_playtime": 90, "min_age": 10, "year_published": 2014, "users_rated": 12000, "categories": [{"id": 0, "name": "City Building"}, {"id": 1, "name": "Medieval"}], "mechanics": [{"id": 0, "name": "Tile Placement"}, {"id": 1, "name": "Auction"}], "designers": ["Ted Alspach"], "publishers": ["Bezier Games"]},
]


async def import_extra_data():
    for game in EXTRA_GAMES:
        game.setdefault("name_zh", "")
        game.setdefault("description_en", "")
        game.setdefault("description_zh", "")
        game.setdefault("thumbnail", "")
        game.setdefault("image", "")
        game.setdefault("local_thumbnail", "")
        game.setdefault("local_image", "")
        game.setdefault("min_age", 0)
        game.setdefault("users_rated", 0)
        game.setdefault("expansions", [])
        game.setdefault("series", [])
        game.setdefault("designers", [])
        game.setdefault("publishers", [])
        game["updated_at"] = datetime.now(timezone.utc)

        await mongo_db.board_games.update_one(
            {"bgg_id": game["bgg_id"]},
            {"$set": game, "$setOnInsert": {"created_at": datetime.now(timezone.utc)}},
            upsert=True,
        )

    print(f"Extra data import complete. {len(EXTRA_GAMES)} games saved.")
